server {
    listen 80;
    server_name my-school-alarm.duckdns.org;

    # HTTP(80)로 접속하면 무조건 HTTPS(443)로 안전하게 돌려보냅니다.
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name my-school-alarm.duckdns.org;

    # 방금 우분투에 발급된 인증서와 비밀키의 경로입니다. (도커 볼륨으로 연결됨)
    ssl_certificate /etc/letsencrypt/live/my-school-alarm.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/my-school-alarm.duckdns.org/privkey.pem;

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}